standardKeyCardList = [
    "Agatha's Soul Cauldron",
    "Vivi Ornitier",
    "Nurturing Pixie",
    "Abhorrent Oculus",
    "Kaito, Bane of Nightmares",
    "No More Lies",
    "Mabel, Heir to Cragflame",
    "Dyadrine, Synthesis Amalgam",
    "Hemosymbic Mite",
    "Sarkhan, Dragon Ascendant",
    "Nova Hellkite",
    "Kona, Rescue Beastie",
    "Unstoppable Slasher",
    "Archenemy's Charm",
    "Ketramose, the New Dawn",
    "Mosswood Dreadknight",
    "Song of Totentanz",
    "Repurposing Bay",
    "Subterranean Schooner",
    "Caretaker's Talent",
    "Wildfire Wickerfolk",
    "Insidious Roots",
    "Marang River Regent",
    "Shiko, Paragon of the Way",
    "Tifa Lockhart",
    "Weapons Manufacturing",
    "Emberheart Challenger",
    "Sephiroth, Fabled SOLDIER",
    "Cosmogrand Zenith",
    "Lumbering Worldwagon",
    "Ouroboroid",
    "Devastating Onslaught",
    "Terror of the Peaks",
    "Bartz and Boko",
    "Monument to Endurance",
]

pioneerKeyCardList = [
    "Sheoldred, the Apocalypse",
    "Arclight Phoenix",
    "Nykthos, Shrine to Nyx",
    "Giada, Font of Hope",
    "Indomitable Creativity",
    "Greasefang, Okiba Boss",
    "Emberheart Challenger",
    "Teferi, Hero of Dominaria",
    "Colossus Hammer",
    "Kumano Faces Kakkazan",
    "Lotus Field",
    "Cori-Steel Cutter",
    "Spell Queller",
    "Ygra, Eater of All",
    "Ensoul Artifact",
    "Cauldron Familiar",
    "Gleeful Demolition",
    "Coppercoat Vanguard",
    "Censor",
    "Raffine, Scheming Seer",
    "Illuminator Virtuoso",
    "Metalwork Colossus",
    "Retraction Helix",
    "Jeskai Ascendancy",
    "Quintorius Kand",
    "Kinnan, Bonder Prodigy",
    "Enigmatic Incarnation",
    "Zur, Eternal Schemer",
    "Bring to Light",
    "Heliod, Sun-Crowned",
    "Nurturing Pixie",
    "Liliana of the Veil",
    "Shiko, Paragon of the Way",
    "Collected Company",
]

modernKeyCardList = [

]

pauperKeyCardList = [
    
]

mtgKeyToArchetypeDict = {
    "Agatha's Soul Cauldron": "Cauldron",
    "Emberheart Challenger": "Mice",
    "Ensoul Artifact": "Ensoul",
    "Sheoldred, the Apocalypse": "Midrange",
    "Arclight Phoenix": "Phoenix",
    "Nykthos, Shrine to Nyx": "Devotion",
    "Giada, Font of Hope": "Angels",
    "Indomitable Creativity": "Creativity",
    "Greasefang, Okiba Boss": "Greasefang",
    "Teferi, Hero of Dominaria": "Control",
    "Colossus Hammer": "Hammer",
    "Kumano Faces Kakkazan": "Aggro",
    "Lotus Field": "Lotus Field",
    "Cori-Steel Cutter": "Cori-Steel",
    "Spell Queller": "Spirits",
    "Ygra, Eater of All": "Ygra Sacrifice",
    "Cauldron Familiar": "Sacrifice",
    "Gleeful Demolition": "Convoke",
    "Coppercoat Vanguard": "Humans",
    "Censor": "Control",
    "Raffine, Scheming Seer": "Raffine",
    "Illuminator Virtuoso": "Heroic",
    "Metalwork Colossus": "Colossus",
    "Retraction Helix": "Helix Combo",
    "Jeskai Ascendancy": "Jeskai Ascendancy Combo",
    "Quintorius Kand": "Discover Combo",
    "Kinnan, Bonder Prodigy": "Kinnan Combo",
    "Enigmatic Incarnation": "Incarnation",
    "Zur, Eternal Schemer": "Zur Overlords",
    "Bring to Light": "Bring to Light",
    "Heliod, Sun-Crowned": "Lifegain",
    "Nurturing Pixie": "Pixie",
    "Liliana of the Veil": "Midrange",
    ### Standard Archetypes
    "Vivi Ornitier": "Vivi",
    "Abhorrent Oculus": "Oculus",
    "Kaito, Bane of Nightmares": "Kaito",
    "No More Lies": "Control",
    "Mabel, Heir to Cragflame": "Mice",
    "Dyadrine, Synthesis Amalgam": "Counters",
    "Hemosymbic Mite": "Mite",
    "Sarkhan, Dragon Ascendant": "Dragons",
    "Nova Hellkite": "Big Red",
    "Kona, Rescue Beastie": "Kona",
    "Unstoppable Slasher": "Midrange",
    "Archenemy's Charm": "Midrange",
    "Ketramose, the New Dawn": "Midrange",
    "Mosswood Dreadknight": "Midrange",
    "Song of Totentanz": "Totentanz",
    "Repurposing Bay": "Repurposing Bay",
    "Subterranean Schooner": "Schooner",
    "Caretaker's Talent": "Tokens",
    "Wildfire Wickerfolk": "Delirium",
    "Insidious Roots": "Roots",
    "Marang River Regent": "Control",
    "Shiko, Paragon of the Way": "Control",
    "Tifa Lockhart": "Landfall",
    "Weapons Manufacturing": "Manufacturing",
    "Sephiroth, Fabled SOLDIER": "Sacrifice",
    "Cosmogrand Zenith": "Cosmogrand",
    "Lumbering Worldwagon": "Worldwagon",
    "Ouroboroid": "Ouroboroid",
    "Devastating Onslaught": "Onslaught",
    "Bartz and Boko": "Birds",
    "Terror of the Peaks": "Terror Combo",
    "Collected Company": "CoCo",
    "Monument to Endurance": "Discard",
}

scryKeepCols = [
    "name",
    "mana_cost",
    "type_line",
    "oracle_text",
    "cmc",
    "power",
    "toughness",
    "colors",
    "color_identity",
    "set",
    "rarity",
    "back_name",
    "back_type_line",
    "back_oracle_text",
    "back_power",
    "back_toughness",
]

mtgColourComboNameDict = {
    "": "Colourless",
    "W": "Mono White",
    "U": "Mono Blue",
    "B": "Mono Black",
    "R": "Mono Red",
    "G": "Mono Green",
    "WU": "Azorius",
    "WB": "Orzhov",
    "WR": "Boros",
    "WG": "Selesnya",
    "UB": "Dimir",
    "UR": "Izzet",
    "UG": "Simic",
    "BR": "Rakdos",
    "BG": "Golgari",
    "RG": "Gruul",
    "WUB": "Esper",
    "WUR": "Jeskai",
    "WUG": "Bant",
    "WBR": "Mardu",
    "WBG": "Abzan",
    "WRG": "Naya",
    "UBR": "Grixis",
    "UBG": "Sultai",
    "URG": "Temur",
    "BRG": "Jund",
    "WUBR": "WUBR",
    "WUBG": "WUBG",
    "WURG": "WURG",
    "WBRG": "WBRG",
    "UBRG": "UBRG",
    "WUBRG": "WUBRG",
}
